### ISSUE TITLE
Config files are now treated as directories:

### ISSUE THREAD

**Issue by onlynone** [SuitestAutomation/suitest-js-api#446]
I'm trying to upgrade to the 3.x js api and it seems like the places where suitest looks for rc files has changed. But I don't understand if it's intentional.

Previously, we had in the project directory a `.suitestrc` file that held config stuff that was common amongst the CI system and developer runs. Then our CI system would export environment variables like `suitest_tokenPassword` to set some values, and we instructed our developers to create a `.suitestrc` file in their `${HOME}` directories with values containing *their* credentials (and preferred deviceId/appConfigId if they were mostly running against one test device).

I just upgraded the lib, made the changes to the `.suitestrc` file in the project directory, and triggered a run. But I'm getting the following error:

```
Error: ENOTDIR: not a directory, scandir '/Users/steven/.suitestrc'
    at Object.readdirSync (fs.js:1021:3)
    at /Users/steven/projects/e2e-tests/node_modules/suitest-js-api/lib/testLauncher/composeConfig.js:130:22
    at Array.forEach (<anonymous>)
    at readRcConfig (/Users/steven/projects/e2e-tests/node_modules/suitest-js-api/lib/testLauncher/composeConfig.js:128:15)
    at composeConfig (/Users/steven/projects/e2e-tests/node_modules/suitest-js-api/lib/testLauncher/composeConfig.js:188:19)
    at Object.handler (/Users/steven/projects/e2e-tests/node_modules/suitest-js-api/lib/testLauncher/commands/run.js:95:37)
    at Object.<anonymous> (/Users/steven/projects/e2e-tests/node_modules/ramda/src/once.js:40:17)
    at Object.handler (/Users/steven/projects/e2e-tests/node_modules/ramda/src/internal/_arity.js:11:19)
    at Object.runCommand (/Users/steven/projects/e2e-tests/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/Users/steven/projects/e2e-tests/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.parse (/Users/steven/projects/e2e-tests/node_modules/yargs/build/lib/yargs.js:584:29)
    at Object.<anonymous> (/Users/steven/projects/e2e-tests/node_modules/suitest-js-api/lib/testLauncher/index.js:13:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:763:16)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/steven/projects/e2e-tests/node_modules/suitest-js-api/bin/suitest:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:763:16)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -20,
  syscall: 'scandir',
  code: 'ENOTDIR',
  path: '/Users/steven/.suitestrc'
}
```

It looks like the way that [`CONFIG_FILES`](https://github.com/SuitestAutomation/suitest-js-api/blob/e57aad7e60514ed0dcf69ec106f489cbe63b7912/lib/testLauncher/composeConfig.js#L25) and [`LOOKUP_DIRS`](https://github.com/SuitestAutomation/suitest-js-api/blob/e57aad7e60514ed0dcf69ec106f489cbe63b7912/lib/testLauncher/composeConfig.js#L39) are defined, it now expects that `~/.suitestrc` should be a directory containing a file named `.suitestrc` (or `.suitestrc.json`, etc). It seems redundant to have the file at `~/.suitestrc/.suitestrc`, but is that correct?

**Comment by JeKachan** [comment]
We would like to thank you for your report. We start working on resolving the current issue.

**Comment by onlynone** [comment]
I think just found another breaking difference in config file processing that I don't think was called out in the documentation anywhere. The only migration docs I could find were here: https://suitest.canny.io/changelog/introducing-js-api-v3 .

In the 2.X library, suitest would merge the configs of all the different `rc` files it found (along with environment variables and command line arguments). This was very useful because we could put general config in the `${projectDir}/.suitestrc` file that would apply to all the code, and then individual developers could put specific configs into `~/.suitestrc`. But, it looks like the 3.X library will stop at the first `rc` file it finds.

And given that the order it searches for config files is:

```
const LOOKUP_DIRS = [
	path.join(HOME_DIR, `.${APP_NAME}rc`),
	path.join(HOME_DIR, `.${APP_NAME}`, 'config'),
	path.join(HOME_DIR, '.config', APP_NAME),
	path.join(HOME_DIR, '.config', APP_NAME, 'config'),
	path.join(ETC_DIR, `.${APP_NAME}rc`),
	path.join(ETC_DIR, APP_NAME, 'config'),
	process.cwd(),
];
```

if there is a `~/.config/suitest/.suitestrc` file, then the `${process.cwd()}/.suitestrc` config file will never be read.

**Comment by onlynone** [comment]
In fact. I'm reading through: https://github.com/SuitestAutomation/suitest-js-api/blob/e57aad7e60514ed0dcf69ec106f489cbe63b7912/lib/testLauncher/composeConfig.js#L120 and it looks like `foundFiles` could never be anything other than an array containing a single element, which is always equal to `mainConfigFilePath`. Is that correct? Is there ever a case where you could have it recognize more than one config file?

**Comment by onlynone** [comment]
The `composeConfig` function: https://github.com/SuitestAutomation/suitest-js-api/blob/e57aad7e60514ed0dcf69ec106f489cbe63b7912/lib/testLauncher/composeConfig.js#L187 also looks like it has some confusing behavior.

It starts off like this:
```
const composeConfig = (argv) => {
	const rcConfig = readRcConfig(argv.configFile);
	const configFilePath = argv.configFile || rcConfig.configFile;
	const userConfig = configFilePath ? readUserConfig(configFilePath) : {};

	const ownArgs = {
		...pickNonNil(suitest.configuration.overridableFields, rcConfig),
		...pickNonNil(suitest.configuration.overridableFields, userConfig),
		...pickNonNil(suitest.configuration.overridableFields, argv),
	};
```

But if you pass `--config-file` into the program, then it looks like `const rcConfig = readRcConfig(argv.configFile);` will parse that file as any of the available config file formats. And then it looks like `configFilePath` will be set to the same path, and it'll be parsed again by the line `const userConfig = configFilePath ? readUserConfig(configFilePath) : {};`. Except this time, `readUserConfig` will only try to parse the file as json:

```
function readUserConfig(path) {
	try {
		return JSON.parse(fs.readFileSync(path));
	} catch (error) {
		throw new SuitestError(invalidUserConfig(path, error.message), error.code);
	}
}
```

So you'll get an exception if your config file is in json5 or yaml or something else. Is that correct?

I think if the config file has already been parsed by `readRcConfig`, then you don't want to try parsing it again and `readUserConfig` should probably be written to accept all the different formats that `readConfigFile` accepts, no?

**Comment by onlynone** [comment]
The docs for [Suitest JavaScript API v3](https://suite.st/docs/suitest-api/setup/#the-configuration-file) do still say:

> **Project setup security**  
> In a real project you should separate the project specific Suitest configuration in the configuration file inside your project folder and commit that file to the VCS. Your private token credentials should stay in the configuration file located in your home folder. Check [RC standard](https://www.npmjs.com/package/rc#standards) for details on precedence.
Launching a test

So it seems like suitest should still be supporting merging multiple files? And potentially still going by the `rc` standards?

**Comment by martinc-suitest** [comment]
Hi Steven,

Let me apologize for the issue you have reported and assure you that we are working on the fix and will release it in the following days.

Regarding your question about merging configuration files, yes it is supported as well as the `rc` standards. 
For more information see [the related section in our docs](https://suite.st/docs/suitest-api/advanced-topics/#merging-configuration-files).

If you need any further details, please contact us through our official channel - support@suite.st.

Kind regards,
Martin

**Comment by onlynone** [comment]
> Regarding your question about merging configuration files, yes it is supported as well as the rc standards.
For more information see [the related section in our docs](https://suite.st/docs/suitest-api/advanced-topics/#merging-configuration-files).

It seems like you only support combining configs via the explicit `extends`keyword. The [`rc` standard](https://www.npmjs.com/package/rc#standards) supports transparent merging of files from all locations:

> All configuration sources that were found will be flattened into one object, so that sources earlier in this list override later ones.
