### ISSUE TITLE
JS code doesn't error on 0 being passed to repeat()

### ISSUE THREAD

**Issue by onlynone** [SuitestAutomation/suitest-js-api#457]
It appears that the JS code checks that the argument to `.repeat(times)` is not negative, but it allows `0`. This seems to cause an error at the network API level to be raised and you get a mysterious `Test command received invalid input` exception. Here's an example of passing `-1` (get immediate error with explanation), `0` (delayed error with non-specific message), and `1` (success) to `.repeat()`:

```
Suitest $ suitest.press(suitest.VRC.RIGHT).repeat(-1).then(res => console.log(res));
Uncaught:
SuitestError: Invalid input provided for .repeat function. Repeat should be positive number
    at REPL27:1:34
    at Script.runInContext (vm.js:143:18)
    at REPLServer.defaultEval (repl.js:486:29)
    at bound (domain.js:413:15)
    at REPLServer.runBound [as eval] (domain.js:424:12)
    at REPLServer.onLine (repl.js:817:10)
    at REPLServer.emit (events.js:315:20)
    at REPLServer.EventEmitter.emit (domain.js:467:12)
    at REPLServer.Interface._onLine (readline.js:337:10)
    at REPLServer.Interface._line (readline.js:666:8)
    at REPLServer.Interface._ttyWrite (readline.js:1010:14)
    at REPLServer.self._ttyWrite (repl.js:907:9)
    at Socket.onkeypress (readline.js:213:10)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at emitKeys (internal/readline/utils.js:345:14)
    at emitKeys.next (<anonymous>)
    at Socket.onData (readline.js:1144:36)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
    at Pipe.callbackTrampoline (internal/async_hooks.js:131:14) {
  code: Symbol(invalidInput),
  type: 'SuitestError'
}
Suitest $ suitest.press(suitest.VRC.RIGHT).repeat(0).then(res => console.log(res));
Promise { <pending> }
Suitest $ Mar 28 11:53:23 XXXX (abc) E Press button RIGHT
Mar 28 11:53:23 XXXX (abc)  ✖ Press button RIGHT
Mar 28 11:53:23 XXXX (abc)    fail: Test command received invalid input
Mar 28 11:53:23 XXXX (abc)      at REPL28:1:34

Suitest $ suitest.press(suitest.VRC.RIGHT).repeat(1).then(res => console.log(res));
Promise { <pending> }
Suitest $ Mar 28 11:53:30 XXXX (abc) E Press button RIGHT
true
```

You may want to make `validatePositiveNumber` reject not just `val < 0`, but `val <=0`. If there are places where you want the existing validation logic, perhaps a `validateNonNegativeNumber` could be added.

**Comment by polomsky** [comment]
Fixed in version 3.7.1
